name: Go CI/CD

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  push:
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.event_name != 'push' || startsWith(github.ref, 'refs/heads/')  # فقط برای شاخه main
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest; goos: linux; ext: ""
          - os: windows-latest; goos: windows; ext: ".exe"
          - os: macos-latest; goos: darwin; ext: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          mkdir -p bin
          go build -v -ldflags "-s -w" -o bin/terminalapp_${{ matrix.goos }}_amd64${{ matrix.ext }} ./cmd/terminalapp/main
      - uses: actions/upload-artifact@v4
        with:
          name: terminalapp-${{ matrix.goos }}-amd64
          path: bin/terminalapp_${{ matrix.goos }}_amd64${{ matrix.ext }}

  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./bin
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
