name: Go CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            ext: ""
          - os: windows-latest
            goos: windows
            ext: ".exe"
          - os: macos-latest
            goos: darwin
            ext: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
      - name: Build artifact
        shell: pwsh
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64
        run: |
          if ($Env:RUNNER_OS -eq 'Windows') {
            New-Item -ItemType Directory -Force -Path bin | Out-Null
          } else {
            mkdir -p bin
          }
          go build -v -ldflags "-s -w" -o "bin/terminalapp_${Env:GOOS}_amd64${{ matrix.ext }}" ./cmd/terminalapp/main
      - uses: actions/upload-artifact@v4
        with:
          name: terminalapp-${{ matrix.goos }}-amd64
          path: bin/terminalapp_${{ matrix.goos }}_amd64${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./bin
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
